spring:
  mail:
    host: smtp.gmail.com
    port: 587

    username: ${GMAIL_USERNAME:test@gmail.com}
    password: ${GMAIL_PASSWORD:test}

    properties:
      mail:
        smtp:
          auth: true

          starttls:
            enable: true