
spring:
  config:
    import:
      - classpath:properties/jwt.yml
      - classpath:properties/security.yml
      - classpath:properties/gmail.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa

  #  sql:
  #    init:
  #      schema-locations: classpath*:database/schema.sql

  profiles:
    active:
      local

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    show-sql: true

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true